### ISSUE TITLE
[feature] Layout 설계

### ISSUE THREAD

**Issue by Jmwasd** [codestates/pt_at_home_client#11]
### ISSUE
- Group:  `client`
- Type: `feature`

### TODO
1. [ ] workout page layout 설계
2. [ ] myrotine page layout 설계
3. [ ] myprofile page layout 설계
