### ISSUE TITLE
[Feature] Setup reducers & actions & store

### ISSUE THREAD

**Issue by shyunlee** [codestates/pt_at_home_client#33]
### ISSUE
- Group:  client
- Type: feature
- Detail: implement reducers & action creator & Redux Store

### TODO
1. [ ] setup reducer function
2. [ ] setup action creator
3. [ ] setup redux store
